### ISSUE TITLE
Add SassDoc

### ISSUE THREAD

**Issue by KittyGiraudel** [davidkpiano/sassdash#7]

**Comment by davidkpiano** [comment]
Sassdoc confirmed to work - still updating documentation to be more aligned with the Sass implementation rather than the JS lodash implementation.

I gitignored the Sassdoc directory but will probably un-ignore it in a `gh-pages` branch: 29870f24724cfee524242dce40e495b4d6ee1b9e

If you install Sassdoc, it should work fine.
